# Generated by Django 5.0.3 on 2024-03-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_delete_albummodel'),
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MusicianModel',
        ),
    ]
