# Generated by Django 5.0.3 on 2024-03-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_alter_album_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='rating',
        ),
        migrations.AddField(
            model_name='album',
            name='ratings',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='4', max_length=1),
        ),
    ]
